name: 01 - Hello World Enterprise

on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: enterprise-arc-runner-set
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
  
  hello:
    runs-on: enterprise-arc-runner-set
    steps:
      - name: Print greeting
        run: echo "Hello, World from arc-runner-set!"
      
      - name: Show runner info
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner arch: $RUNNER_ARCH"
          uname -a
      
      - name: Current date and time
        run: date
