name: 02 - Multiple Jobs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: arc-runner-set
    steps:
      - name: Job 1 - Step 1
        run: echo "This is job 1, step 1"
      
      - name: Job 1 - Step 2
        run: echo "This is job 1, step 2"
  
  job2:
    runs-on: arc-runner-set
    steps:
      - name: Job 2 - Step 1
        run: echo "This is job 2, step 1"
      
      - name: Job 2 - Step 2
        run: echo "This is job 2, step 2"
  
  job3:
    runs-on: arc-runner-set
    steps:
      - name: Job 3 - Step 1
        run: echo "This is job 3, step 1"
      
      - name: Job 3 - Step 2
        run: echo "This is job 3, step 2"
